//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoMac.Main.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-2NL1B67\\SQLEXPRESS,4858;Initial Catalog=DbProvider;Persist Se" +
            "curity Info=True;User ID=nhan;Password=123456")]
        public string DbProviderConnectionString {
            get {
                return ((string)(this["DbProviderConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string KitchenType {
            get {
                return ((string)(this["KitchenType"]));
            }
            set {
                this["KitchenType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int TimeCounter {
            get {
                return ((int)(this["TimeCounter"]));
            }
            set {
                this["TimeCounter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ForceColorToGo {
            get {
                return ((global::System.Drawing.Color)(this["ForceColorToGo"]));
            }
            set {
                this["ForceColorToGo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public int FontSizePrint {
            get {
                return ((int)(this["FontSizePrint"]));
            }
            set {
                this["FontSizePrint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int PaddingSizePrint {
            get {
                return ((int)(this["PaddingSizePrint"]));
            }
            set {
                this["PaddingSizePrint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color ColorItemChange {
            get {
                return ((global::System.Drawing.Color)(this["ColorItemChange"]));
            }
            set {
                this["ColorItemChange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 128, 255")]
        public global::System.Drawing.Color ColorBackgroundToGo {
            get {
                return ((global::System.Drawing.Color)(this["ColorBackgroundToGo"]));
            }
            set {
                this["ColorBackgroundToGo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 192, 0")]
        public global::System.Drawing.Color ColorBackgroundItemChange {
            get {
                return ((global::System.Drawing.Color)(this["ColorBackgroundItemChange"]));
            }
            set {
                this["ColorBackgroundItemChange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SkinStyle {
            get {
                return ((string)(this["SkinStyle"]));
            }
            set {
                this["SkinStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WebSiteLocation {
            get {
                return ((string)(this["WebSiteLocation"]));
            }
            set {
                this["WebSiteLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ImagePath {
            get {
                return ((string)(this["ImagePath"]));
            }
            set {
                this["ImagePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoCompleteAndPrint {
            get {
                return ((bool)(this["AutoCompleteAndPrint"]));
            }
            set {
                this["AutoCompleteAndPrint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int NumberOfReprint {
            get {
                return ((int)(this["NumberOfReprint"]));
            }
            set {
                this["NumberOfReprint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int AutoPrintAfterSecond {
            get {
                return ((int)(this["AutoPrintAfterSecond"]));
            }
            set {
                this["AutoPrintAfterSecond"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowMultiInstance {
            get {
                return ((bool)(this["AllowMultiInstance"]));
            }
            set {
                this["AllowMultiInstance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Printers {
            get {
                return ((string)(this["Printers"]));
            }
            set {
                this["Printers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PrintBarCode {
            get {
                return ((bool)(this["PrintBarCode"]));
            }
            set {
                this["PrintBarCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int NumOfGroupTable {
            get {
                return ((int)(this["NumOfGroupTable"]));
            }
            set {
                this["NumOfGroupTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int VerticalSplitGroupTablePosition {
            get {
                return ((int)(this["VerticalSplitGroupTablePosition"]));
            }
            set {
                this["VerticalSplitGroupTablePosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int HorizontalSplitGroupTablePosition {
            get {
                return ((int)(this["HorizontalSplitGroupTablePosition"]));
            }
            set {
                this["HorizontalSplitGroupTablePosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowGroupTable {
            get {
                return ((bool)(this["ShowGroupTable"]));
            }
            set {
                this["ShowGroupTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowFilterTable {
            get {
                return ((bool)(this["ShowFilterTable"]));
            }
            set {
                this["ShowFilterTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color ForceColorLageSize {
            get {
                return ((global::System.Drawing.Color)(this["ForceColorLageSize"]));
            }
            set {
                this["ForceColorLageSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nhỏ")]
        public string SizeSmall {
            get {
                return ((string)(this["SizeSmall"]));
            }
            set {
                this["SizeSmall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lớn")]
        public string SizeLarge {
            get {
                return ((string)(this["SizeLarge"]));
            }
            set {
                this["SizeLarge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Windows\\Media\\Ring07.wav")]
        public string SoundUrl {
            get {
                return ((string)(this["SoundUrl"]));
            }
            set {
                this["SoundUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TicketWidthSize {
            get {
                return ((int)(this["TicketWidthSize"]));
            }
            set {
                this["TicketWidthSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TicketHeightSize {
            get {
                return ((int)(this["TicketHeightSize"]));
            }
            set {
                this["TicketHeightSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TicketFontSize {
            get {
                return ((int)(this["TicketFontSize"]));
            }
            set {
                this["TicketFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ForceColor {
            get {
                return ((global::System.Drawing.Color)(this["ForceColor"]));
            }
            set {
                this["ForceColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color ForceColor1 {
            get {
                return ((global::System.Drawing.Color)(this["ForceColor1"]));
            }
            set {
                this["ForceColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color BackgroundColorEmergency {
            get {
                return ((global::System.Drawing.Color)(this["BackgroundColorEmergency"]));
            }
            set {
                this["BackgroundColorEmergency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Transparent")]
        public global::System.Drawing.Color BackgrdColorQty {
            get {
                return ((global::System.Drawing.Color)(this["BackgrdColorQty"]));
            }
            set {
                this["BackgrdColorQty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ForceColorQty {
            get {
                return ((global::System.Drawing.Color)(this["ForceColorQty"]));
            }
            set {
                this["ForceColorQty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color ForceColorQty1 {
            get {
                return ((global::System.Drawing.Color)(this["ForceColorQty1"]));
            }
            set {
                this["ForceColorQty1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int FontSizeQty {
            get {
                return ((int)(this["FontSizeQty"]));
            }
            set {
                this["FontSizeQty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoCompleteAndPrintSpecialItem {
            get {
                return ((bool)(this["AutoCompleteAndPrintSpecialItem"]));
            }
            set {
                this["AutoCompleteAndPrintSpecialItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MCP30 - Ethernet:TCP:")]
        public string PrinterOpenCashDrawerName {
            get {
                return ((string)(this["PrinterOpenCashDrawerName"]));
            }
            set {
                this["PrinterOpenCashDrawerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HandleTicketFromSquare {
            get {
                return ((bool)(this["HandleTicketFromSquare"]));
            }
            set {
                this["HandleTicketFromSquare"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MCP30 - Ethernet:TCP:")]
        public string LookUpPrinterForSpecialItem {
            get {
                return ((string)(this["LookUpPrinterForSpecialItem"]));
            }
            set {
                this["LookUpPrinterForSpecialItem"] = value;
            }
        }
    }
}
