//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoMac.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int AppointmentID { get; set; }
        public Nullable<System.DateTime> OnDate { get; set; }
        public string OnTime { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPhone { get; set; }
        public Nullable<int> KitNumber { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string Description { get; set; }
        public string Services { get; set; }
        public Nullable<int> TimeIdx { get; set; }
        public Nullable<int> TimeSec { get; set; }
        public Nullable<int> StatusA { get; set; }
        public Nullable<int> StatusS { get; set; }
        public string StatusStr { get; set; }
        public Nullable<bool> Locked { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> OnDay { get; set; }
        public Nullable<int> OnMonth { get; set; }
        public Nullable<int> OnYear { get; set; }
        public string DateKey { get; set; }
        public Nullable<int> OnWeek { get; set; }
        public string WeekKey { get; set; }
        public Nullable<int> OnBiWeek { get; set; }
        public string BiWeekKey { get; set; }
        public Nullable<int> OnSimMonth { get; set; }
        public string SimMonthKey { get; set; }
        public Nullable<int> OnQuarter { get; set; }
        public string QuarterKey { get; set; }
        public Nullable<bool> NewObj { get; set; }
        public Nullable<bool> ChgeObj { get; set; }
        public Nullable<bool> SentObj { get; set; }
        public Nullable<bool> RemindedSMS { get; set; }
        public Nullable<bool> RemindedEmail { get; set; }
        public Nullable<int> Scheduled { get; set; }
        public Nullable<bool> ByEmail { get; set; }
        public Nullable<bool> BySMS { get; set; }
        public Nullable<bool> ByRequest { get; set; }
        public string TechMobile { get; set; }
        public string TechName { get; set; }
        public string TechEmail { get; set; }
        public Nullable<int> ColorIdx { get; set; }
        public Nullable<int> ColorArgb { get; set; }
        public Nullable<System.DateTime> EditTimestamp { get; set; }
        public Nullable<int> RecordState { get; set; }
        public string RecordGUID { get; set; }
    }
}
