//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoMac.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardInfo
    {
        public int CardInfoID { get; set; }
        public Nullable<System.DateTime> OnDate { get; set; }
        public string TID { get; set; }
        public string MID { get; set; }
        public string DID { get; set; }
        public Nullable<int> CardType { get; set; }
        public string CardName { get; set; }
        public string HolderName { get; set; }
        public string Acc4Digit { get; set; }
        public string Account { get; set; }
        public string ExpDate { get; set; }
        public Nullable<int> ExpYear { get; set; }
        public Nullable<int> ExpMonth { get; set; }
        public string Track1 { get; set; }
        public string Track2 { get; set; }
        public string Address { get; set; }
        public string Zip { get; set; }
        public string CardGUID { get; set; }
        public Nullable<int> Action { get; set; }
        public string ActionStr { get; set; }
        public Nullable<bool> Settled { get; set; }
        public string Reference { get; set; }
        public string AuthCode { get; set; }
        public string TransactionID { get; set; }
        public string TDate { get; set; }
        public string ACI { get; set; }
        public string OrderId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Tips { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string StoreName { get; set; }
        public string StoreAddress { get; set; }
        public string StoreCity { get; set; }
        public string StoreState { get; set; }
        public string StoreZip { get; set; }
        public string StorePhone { get; set; }
        public Nullable<int> RecordState { get; set; }
        public string RecordGUID { get; set; }
    }
}
