//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoMac.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerType
    {
        public int CustomerTypeID { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> ApplyDiscount { get; set; }
        public string CustTypeStr { get; set; }
        public Nullable<decimal> DiscountAmt { get; set; }
        public Nullable<float> DiscountRate { get; set; }
        public Nullable<bool> HasExpireDate { get; set; }
        public Nullable<int> OIndex { get; set; }
        public Nullable<int> RecordState { get; set; }
        public string RecordGUID { get; set; }
    }
}
