//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoMac.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerID { get; set; }
        public string BarCode { get; set; }
        public Nullable<bool> Favorite { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string HomePhone { get; set; }
        public string CellPhone { get; set; }
        public Nullable<int> KitNum { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string EmpPreferName { get; set; }
        public string EmpServiceLast { get; set; }
        public Nullable<System.DateTime> CustSince { get; set; }
        public Nullable<System.DateTime> LastVisit { get; set; }
        public Nullable<int> NumVisit { get; set; }
        public Nullable<decimal> TotalSpend { get; set; }
        public string DriverLicense { get; set; }
        public string ImageFileName { get; set; }
        public string ReferencesNotes { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public Nullable<bool> ByMail { get; set; }
        public Nullable<bool> ByEmail { get; set; }
        public Nullable<bool> BySMS { get; set; }
        public string Profile1 { get; set; }
        public string Business { get; set; }
        public string Email { get; set; }
        public string Profile2 { get; set; }
        public string Profile3 { get; set; }
        public Nullable<int> HearFromUsID { get; set; }
        public Nullable<decimal> UnPaid { get; set; }
        public Nullable<System.DateTime> DiscountDate { get; set; }
        public Nullable<decimal> RewardPoints { get; set; }
        public Nullable<float> RewardRate { get; set; }
        public Nullable<int> OnDay { get; set; }
        public Nullable<int> OnMonth { get; set; }
        public Nullable<int> OnYear { get; set; }
        public Nullable<System.DateTime> OnDate { get; set; }
        public string DateKey { get; set; }
        public Nullable<int> OnWeek { get; set; }
        public string WeekKey { get; set; }
        public Nullable<int> OnBiWeek { get; set; }
        public string BiWeekKey { get; set; }
        public Nullable<int> OnSimMonth { get; set; }
        public string SimMonthKey { get; set; }
        public Nullable<int> OnQuarter { get; set; }
        public string QuarterKey { get; set; }
        public Nullable<bool> NewObj { get; set; }
        public Nullable<bool> ChgeObj { get; set; }
        public Nullable<bool> SentObj { get; set; }
        public string PatientNum { get; set; }
        public Nullable<System.DateTime> PExpireDate { get; set; }
        public Nullable<System.DateTime> DExpireDate { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Selected { get; set; }
        public Nullable<decimal> OpenBalance { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public Nullable<decimal> EstimateTotal { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string FileAs { get; set; }
        public Nullable<bool> SameAsBill { get; set; }
        public string AddressS { get; set; }
        public string CityS { get; set; }
        public string StateS { get; set; }
        public string ZipCodeS { get; set; }
        public string ContactName { get; set; }
        public string ContactNameAtl { get; set; }
        public string Fax { get; set; }
        public string HomePhoneAtl { get; set; }
        public string Terms { get; set; }
        public Nullable<int> TermsID { get; set; }
        public string CustTypeStr { get; set; }
        public Nullable<int> CustType { get; set; }
        public string SaleRep { get; set; }
        public Nullable<int> SaleRepID { get; set; }
        public string AccountNo { get; set; }
        public string PayTypeStr { get; set; }
        public Nullable<int> PayType { get; set; }
        public string CreditCardNo { get; set; }
        public Nullable<int> ExpYear { get; set; }
        public Nullable<int> ExpMonth { get; set; }
        public string HolderName { get; set; }
        public string CardAddress { get; set; }
        public string CardZip { get; set; }
        public string ReSaleNo { get; set; }
        public string EditSequence { get; set; }
        public string AddressAddr1 { get; set; }
        public string AddressAddr2 { get; set; }
        public string AddressAddr3 { get; set; }
        public string AddressAddr4 { get; set; }
        public string AddressAddr1S { get; set; }
        public string AddressAddr2S { get; set; }
        public string AddressAddr3S { get; set; }
        public string AddressAddr4S { get; set; }
        public string AddressAddr5 { get; set; }
        public Nullable<bool> International { get; set; }
        public string AddressAddr5S { get; set; }
        public string Country { get; set; }
        public Nullable<int> OMarkState { get; set; }
        public Nullable<System.DateTime> EditTimestamp { get; set; }
        public Nullable<int> RecordState { get; set; }
        public string RecordGUID { get; set; }
    }
}
