//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoMac.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyDraw
    {
        public int DailyDrawID { get; set; }
        public string Description { get; set; }
        public string Withdrawer { get; set; }
        public Nullable<System.DateTime> DrawDate { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> OnDay { get; set; }
        public Nullable<int> OnMonth { get; set; }
        public Nullable<int> OnYear { get; set; }
        public Nullable<System.DateTime> OnDate { get; set; }
        public string DateKey { get; set; }
        public Nullable<int> OnWeek { get; set; }
        public string WeekKey { get; set; }
        public Nullable<int> OnBiWeek { get; set; }
        public string BiWeekKey { get; set; }
        public Nullable<int> OnSimMonth { get; set; }
        public string SimMonthKey { get; set; }
        public Nullable<int> OnQuarter { get; set; }
        public string QuarterKey { get; set; }
        public Nullable<bool> NewObj { get; set; }
        public Nullable<bool> ChgeObj { get; set; }
        public Nullable<bool> SentObj { get; set; }
        public Nullable<int> TranID { get; set; }
        public Nullable<int> AdminID { get; set; }
        public Nullable<System.DateTime> EditTimestamp { get; set; }
        public Nullable<int> RecordState { get; set; }
        public string RecordGUID { get; set; }
    }
}
