//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoMac.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dictionary
    {
        public string Dic_Keyword { get; set; }
        public string Dic_SourceLanguage { get; set; }
        public string Dic_TargetLanguage { get; set; }
    }
}
