//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoMac.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.PhoHa7_Attendance = new HashSet<PhoHa7_Attendance>();
            this.PhoHa7_Sys_User_Permission = new HashSet<PhoHa7_Sys_User_Permission>();
            this.PhoHa7_UserRole = new HashSet<PhoHa7_UserRole>();
        }
    
        public int EmployeeID { get; set; }
        public Nullable<int> CurTicketNum { get; set; }
        public Nullable<bool> Active { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string HomePhone { get; set; }
        public string CellPhone { get; set; }
        public string SSN { get; set; }
        public Nullable<int> ContractType { get; set; }
        public Nullable<decimal> Limit { get; set; }
        public Nullable<float> CPercent { get; set; }
        public Nullable<int> ImageID { get; set; }
        public string ImageFPath { get; set; }
        public Nullable<int> Page { get; set; }
        public Nullable<int> Row { get; set; }
        public Nullable<int> Col { get; set; }
        public Nullable<int> ButtonColor { get; set; }
        public Nullable<int> TextColor { get; set; }
        public string SecurityCode { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public Nullable<bool> ShowName { get; set; }
        public Nullable<bool> CannotOpenDrawer { get; set; }
        public Nullable<bool> ApplyTipCheck { get; set; }
        public Nullable<bool> NoAppointment { get; set; }
        public Nullable<bool> NoPicture { get; set; }
        public string RealName { get; set; }
        public string Tittle { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> ZOrder { get; set; }
        public Nullable<int> PayrollOptions { get; set; }
        public Nullable<int> WorkDays { get; set; }
        public Nullable<int> TOrder { get; set; }
        public Nullable<decimal> BorrowCash { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> CheckPayRate { get; set; }
        public Nullable<decimal> CheckPayAmt { get; set; }
        public Nullable<decimal> Rate2 { get; set; }
        public Nullable<System.DateTime> MonStartTime { get; set; }
        public Nullable<System.DateTime> MonEndedTime { get; set; }
        public Nullable<System.DateTime> TueStartTime { get; set; }
        public Nullable<float> CommPercent { get; set; }
        public Nullable<int> CurDTicketNum { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<bool> TActive { get; set; }
        public Nullable<bool> NoReceipt { get; set; }
        public Nullable<bool> YouGotMail { get; set; }
        public Nullable<bool> OtherApp { get; set; }
        public Nullable<int> MemoMailID { get; set; }
        public Nullable<int> BatchNumber { get; set; }
        public Nullable<int> ItemsNumber { get; set; }
        public Nullable<bool> LogIn { get; set; }
        public Nullable<System.DateTime> LogTimeI { get; set; }
        public Nullable<bool> LogOut { get; set; }
        public Nullable<System.DateTime> LogTimeO { get; set; }
        public Nullable<int> LogTimeID { get; set; }
        public byte[] Template1 { get; set; }
        public byte[] Template2 { get; set; }
        public Nullable<int> OnDay { get; set; }
        public Nullable<int> OnMonth { get; set; }
        public Nullable<int> OnYear { get; set; }
        public Nullable<System.DateTime> OnDate { get; set; }
        public string DateKey { get; set; }
        public Nullable<int> OnWeek { get; set; }
        public string WeekKey { get; set; }
        public Nullable<int> OnBiWeek { get; set; }
        public string BiWeekKey { get; set; }
        public Nullable<int> OnSimMonth { get; set; }
        public string SimMonthKey { get; set; }
        public Nullable<int> OnQuarter { get; set; }
        public string QuarterKey { get; set; }
        public Nullable<bool> NewObj { get; set; }
        public Nullable<bool> ChgeObj { get; set; }
        public Nullable<bool> SentObj { get; set; }
        public string LUserName { get; set; }
        public string LPassword { get; set; }
        public Nullable<bool> Administrator { get; set; }
        public Nullable<int> PayrollID { get; set; }
        public string OMID { get; set; }
        public string MID { get; set; }
        public string TID { get; set; }
        public string DeviceID { get; set; }
        public string DID { get; set; }
        public string DIDATL { get; set; }
        public Nullable<bool> IsHasMerchant { get; set; }
        public string FirstName { get; set; }
        public string MidName { get; set; }
        public string LastName { get; set; }
        public string NickName { get; set; }
        public string FileAs { get; set; }
        public Nullable<bool> ShowNick { get; set; }
        public Nullable<bool> ShowBirth { get; set; }
        public string Email { get; set; }
        public Nullable<int> SecureLevel { get; set; }
        public Nullable<int> iPage { get; set; }
        public Nullable<float> ixPos { get; set; }
        public Nullable<float> iyPos { get; set; }
        public Nullable<float> iWidth { get; set; }
        public Nullable<float> iHeight { get; set; }
        public Nullable<float> iFontSize { get; set; }
        public string iButColor { get; set; }
        public string iTextColor { get; set; }
        public Nullable<System.DateTime> TueEndedTime { get; set; }
        public Nullable<System.DateTime> WedStartTime { get; set; }
        public Nullable<System.DateTime> WedEndedTime { get; set; }
        public Nullable<System.DateTime> ThuStartTime { get; set; }
        public Nullable<System.DateTime> ThuEndedTime { get; set; }
        public Nullable<System.DateTime> FriStartTime { get; set; }
        public Nullable<System.DateTime> FriEndedTime { get; set; }
        public Nullable<System.DateTime> SatStartTime { get; set; }
        public Nullable<System.DateTime> SatEndedTime { get; set; }
        public Nullable<System.DateTime> SunStartTime { get; set; }
        public Nullable<System.DateTime> SunEndedTime { get; set; }
        public Nullable<bool> IsAUGST { get; set; }
        public Nullable<int> MarriedStatus { get; set; }
        public Nullable<int> Dependent { get; set; }
        public Nullable<decimal> Withheld { get; set; }
        public Nullable<bool> Examption { get; set; }
        public Nullable<int> RecordState { get; set; }
        public string RecordGUID { get; set; }
        public string TIDATL { get; set; }
        public Nullable<decimal> AddtionFee { get; set; }
        public Nullable<int> AvailableTime { get; set; }
        public string Username { get; set; }
        public Nullable<int> Language { get; set; }
    
        public virtual ICollection<PhoHa7_Attendance> PhoHa7_Attendance { get; set; }
        public virtual ICollection<PhoHa7_Sys_User_Permission> PhoHa7_Sys_User_Permission { get; set; }
        public virtual ICollection<PhoHa7_UserRole> PhoHa7_UserRole { get; set; }
    }
}
