//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoMac.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Error
    {
        public int ErrorID { get; set; }
        public string ErrorText { get; set; }
        public string ErrorDetails { get; set; }
        public Nullable<System.DateTime> ErrorDate { get; set; }
        public string ErrorType { get; set; }
        public string InnerException { get; set; }
        public string InnerSource { get; set; }
        public string InnerExceptionStackTrace { get; set; }
    }
}
