//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoMac.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpProduct
    {
        public int ExpenseID { get; set; }
        public string ExpenseName { get; set; }
        public Nullable<int> ExpCatID { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> ButtonColor { get; set; }
        public Nullable<int> TextColor { get; set; }
        public Nullable<int> Page { get; set; }
        public Nullable<int> Col { get; set; }
        public Nullable<int> Row { get; set; }
        public string ProductImage { get; set; }
        public Nullable<int> OnDay { get; set; }
        public Nullable<int> OnMonth { get; set; }
        public Nullable<int> OnYear { get; set; }
        public Nullable<System.DateTime> OnDate { get; set; }
        public string DateKey { get; set; }
        public Nullable<int> OnWeek { get; set; }
        public string WeekKey { get; set; }
        public Nullable<int> OnBiWeek { get; set; }
        public string BiWeekKey { get; set; }
        public Nullable<int> OnSimMonth { get; set; }
        public string SimMonthKey { get; set; }
        public Nullable<int> OnQuarter { get; set; }
        public string QuarterKey { get; set; }
        public Nullable<bool> NewObj { get; set; }
        public Nullable<bool> ChgeObj { get; set; }
        public Nullable<bool> SentObj { get; set; }
        public Nullable<int> RecordState { get; set; }
        public string RecordGUID { get; set; }
    }
}
