//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoMac.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiftHistory
    {
        public int GiftHistoryID { get; set; }
        public int TranID { get; set; }
        public string BarCode { get; set; }
        public System.DateTime UsedDate { get; set; }
        public Nullable<decimal> UsedAmt { get; set; }
        public Nullable<decimal> AddAmt { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> DTicketNum { get; set; }
        public Nullable<int> TicketNum { get; set; }
        public string FullName { get; set; }
        public Nullable<bool> RetType { get; set; }
        public Nullable<int> RecType { get; set; }
        public Nullable<int> OnDay { get; set; }
        public Nullable<int> OnMonth { get; set; }
        public Nullable<int> OnYear { get; set; }
        public Nullable<System.DateTime> OnDate { get; set; }
        public string DateKey { get; set; }
        public Nullable<int> OnWeek { get; set; }
        public string WeekKey { get; set; }
        public Nullable<int> OnBiWeek { get; set; }
        public string BiWeekKey { get; set; }
        public Nullable<int> OnSimMonth { get; set; }
        public string SimMonthKey { get; set; }
        public Nullable<int> OnQuarter { get; set; }
        public string QuarterKey { get; set; }
        public Nullable<bool> NewObj { get; set; }
        public Nullable<bool> ChgeObj { get; set; }
        public Nullable<bool> SentObj { get; set; }
        public Nullable<int> RecordState { get; set; }
        public string RecordGUID { get; set; }
        public Nullable<System.DateTime> EditTimestamp { get; set; }
        public Nullable<int> AdminID { get; set; }
        public Nullable<int> ChainID { get; set; }
    }
}
