//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoMac.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiftCert
    {
        public int GiftCertID { get; set; }
        public string BarCode { get; set; }
        public Nullable<decimal> Issued { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> LastUsed { get; set; }
        public string FullName { get; set; }
        public Nullable<byte> PaidType { get; set; }
        public string CardCode { get; set; }
        public Nullable<decimal> PaidCash { get; set; }
        public Nullable<decimal> PaidGift { get; set; }
        public Nullable<decimal> PaidCredit { get; set; }
        public Nullable<decimal> PaidCheck { get; set; }
        public Nullable<bool> Voided { get; set; }
        public Nullable<bool> RetType { get; set; }
        public Nullable<bool> LostStolen { get; set; }
        public Nullable<bool> ReUsed { get; set; }
        public string RecText { get; set; }
        public Nullable<int> RecType { get; set; }
        public Nullable<int> TranID { get; set; }
        public Nullable<int> OnDay { get; set; }
        public Nullable<int> OnMonth { get; set; }
        public Nullable<int> OnYear { get; set; }
        public Nullable<System.DateTime> OnDate { get; set; }
        public string DateKey { get; set; }
        public Nullable<int> OnWeek { get; set; }
        public string WeekKey { get; set; }
        public Nullable<int> OnBiWeek { get; set; }
        public string BiWeekKey { get; set; }
        public Nullable<int> OnSimMonth { get; set; }
        public string SimMonthKey { get; set; }
        public Nullable<int> OnQuarter { get; set; }
        public string QuarterKey { get; set; }
        public Nullable<bool> NewObj { get; set; }
        public Nullable<bool> ChgeObj { get; set; }
        public Nullable<bool> SentObj { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> PaidMisc { get; set; }
        public Nullable<decimal> PaidGCard { get; set; }
        public Nullable<int> AdminID { get; set; }
        public Nullable<int> PayrollID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<int> CoachID { get; set; }
        public string CoachName { get; set; }
        public Nullable<int> SaleRepID { get; set; }
        public string SaleRepName { get; set; }
        public Nullable<int> CardID { get; set; }
        public Nullable<bool> IsExterm { get; set; }
        public Nullable<int> RecordState { get; set; }
        public string RecordGUID { get; set; }
        public Nullable<System.DateTime> EditTimestamp { get; set; }
        public Nullable<decimal> GST { get; set; }
        public Nullable<decimal> NetSale { get; set; }
        public Nullable<int> ChainID { get; set; }
    }
}
