//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoMac.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoHa7_UserRole
    {
        public int UR_Username { get; set; }
        public int UR_Role_Id { get; set; }
        public string UR_Description { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual PhoHa7_Sys_Role PhoHa7_Sys_Role { get; set; }
    }
}
