//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoMac.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoHa7_ProcTickets
    {
        public int TicketID { get; set; }
        public string CustomerName { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<int> TicketNum { get; set; }
        public Nullable<System.DateTime> DateTimeIssue { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string TableName { get; set; }
        public Nullable<int> DTicketNum { get; set; }
        public Nullable<bool> TakeOut { get; set; }
        public Nullable<bool> Done { get; set; }
        public Nullable<bool> ToKitchen { get; set; }
        public Nullable<bool> IsChange { get; set; }
        public Nullable<int> TicketID_Root { get; set; }
        public Nullable<int> TableID { get; set; }
        public Nullable<bool> Emergency { get; set; }
        public string transaction_id { get; set; }
        public string client_transaction_id { get; set; }
    }
}
