//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoMac.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoHa7_Sys_Role
    {
        public PhoHa7_Sys_Role()
        {
            this.PhoHa7_Sys_Role_Permission = new HashSet<PhoHa7_Sys_Role_Permission>();
            this.PhoHa7_UserRole = new HashSet<PhoHa7_UserRole>();
        }
    
        public int Role_ID { get; set; }
        public string Role_Name { get; set; }
        public Nullable<bool> Role_IsSystem { get; set; }
        public string Role_Description { get; set; }
        public Nullable<int> Role_Level { get; set; }
    
        public virtual ICollection<PhoHa7_Sys_Role_Permission> PhoHa7_Sys_Role_Permission { get; set; }
        public virtual ICollection<PhoHa7_UserRole> PhoHa7_UserRole { get; set; }
    }
}
