//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoMac.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Category> Categories { get; set; }
        public DbSet<DelItem> DelItems { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<PhoHa7_Attendance> PhoHa7_Attendance { get; set; }
        public DbSet<PhoHa7_FilterSaleItem> PhoHa7_FilterSaleItem { get; set; }
        public DbSet<PhoHa7_ProcSaleItem> PhoHa7_ProcSaleItem { get; set; }
        public DbSet<PhoHa7_ProcTickets> PhoHa7_ProcTickets { get; set; }
        public DbSet<PhoHa7_ProductType> PhoHa7_ProductType { get; set; }
        public DbSet<PhoHa7_Sys_Object> PhoHa7_Sys_Object { get; set; }
        public DbSet<PhoHa7_Sys_Option> PhoHa7_Sys_Option { get; set; }
        public DbSet<PhoHa7_Sys_Role> PhoHa7_Sys_Role { get; set; }
        public DbSet<PhoHa7_Sys_Role_Permission> PhoHa7_Sys_Role_Permission { get; set; }
        public DbSet<PhoHa7_Sys_User_Permission> PhoHa7_Sys_User_Permission { get; set; }
        public DbSet<PhoHa7_UserRole> PhoHa7_UserRole { get; set; }
        public DbSet<ProcSaleItem> ProcSaleItems { get; set; }
        public DbSet<ProcTicket> ProcTickets { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<ProductType> ProductTypes { get; set; }
        public DbSet<SaleItem> SaleItems { get; set; }
        public DbSet<TabCategory> TabCategories { get; set; }
        public DbSet<Table> Tables { get; set; }
        public DbSet<Ticket> Tickets { get; set; }
        public DbSet<PhoHa7_Machine> PhoHa7_Machine { get; set; }
        public DbSet<PhoHa7_CardProcess> PhoHa7_CardProcess { get; set; }
        public DbSet<Appointment> Appointments { get; set; }
        public DbSet<CardInfo> CardInfos { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<CustomerType> CustomerTypes { get; set; }
        public DbSet<DailyDraw> DailyDraws { get; set; }
        public DbSet<Error> Errors { get; set; }
        public DbSet<ExpCategory> ExpCategories { get; set; }
        public DbSet<ExpProduct> ExpProducts { get; set; }
        public DbSet<GiftCert> GiftCerts { get; set; }
        public DbSet<GiftHistory> GiftHistories { get; set; }
        public DbSet<Message> Messages { get; set; }
        public DbSet<PaymentType> PaymentTypes { get; set; }
        public DbSet<ReasonItem> ReasonItems { get; set; }
        public DbSet<DaySale> DaySales { get; set; }
        public DbSet<Dictionary> Dictionaries { get; set; }
        public DbSet<Product_Size> Product_Size { get; set; }
        public DbSet<Product_SizeDetails> Product_SizeDetails { get; set; }
    }
}
