//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoMac.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoHa7_CardProcess
    {
        public int ID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string CardNumber { get; set; }
        public string CardName { get; set; }
        public string CardExpire { get; set; }
        public string CardCVV { get; set; }
        public string TransactionID { get; set; }
        public string CardType { get; set; }
        public string Entry { get; set; }
        public Nullable<decimal> Tip { get; set; }
    }
}
