//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoMac.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoHa7_Sys_Option
    {
        public string Opt_ID { get; set; }
        public string Opt_Value { get; set; }
        public Nullable<int> Opt_System { get; set; }
        public string Opt_Group { get; set; }
        public string Opt_Description { get; set; }
    }
}
