//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoMac.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoHa7_Attendance
    {
        public int Att_AttendanceID { get; set; }
        public Nullable<int> Att_EmployeeID { get; set; }
        public string Att_EmployeeName { get; set; }
        public Nullable<double> Day1 { get; set; }
        public Nullable<double> Day2 { get; set; }
        public Nullable<double> Day3 { get; set; }
        public Nullable<double> Day4 { get; set; }
        public Nullable<double> Day5 { get; set; }
        public Nullable<double> Day6 { get; set; }
        public Nullable<double> Day7 { get; set; }
        public Nullable<double> Day8 { get; set; }
        public Nullable<double> Day9 { get; set; }
        public Nullable<double> Day10 { get; set; }
        public Nullable<double> Day11 { get; set; }
        public Nullable<double> Day12 { get; set; }
        public Nullable<double> Day13 { get; set; }
        public Nullable<double> Day14 { get; set; }
        public Nullable<double> Day15 { get; set; }
        public Nullable<double> Day16 { get; set; }
        public Nullable<double> Day17 { get; set; }
        public Nullable<double> Day18 { get; set; }
        public Nullable<double> Day19 { get; set; }
        public Nullable<double> Day20 { get; set; }
        public Nullable<double> Day21 { get; set; }
        public Nullable<double> Day22 { get; set; }
        public Nullable<double> Day23 { get; set; }
        public Nullable<double> Day24 { get; set; }
        public Nullable<double> Day25 { get; set; }
        public Nullable<double> Day26 { get; set; }
        public Nullable<double> Day27 { get; set; }
        public Nullable<double> Day28 { get; set; }
        public Nullable<double> Day29 { get; set; }
        public Nullable<double> Day30 { get; set; }
        public Nullable<double> Day31 { get; set; }
        public Nullable<double> Att_TotalDays { get; set; }
        public Nullable<int> Att_Month { get; set; }
        public Nullable<int> Att_Year { get; set; }
        public Nullable<decimal> Att_AmountCheck { get; set; }
        public Nullable<decimal> Att_AmountCash { get; set; }
        public Nullable<decimal> Att_AmountExtra { get; set; }
        public Nullable<decimal> Att_AmountSubtract { get; set; }
        public Nullable<decimal> Att_AmountTotal { get; set; }
        public string Att_Description { get; set; }
        public Nullable<decimal> Att_Rate { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
