//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoMac.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoHa7_ProductType
    {
        public int ProductTypeID { get; set; }
        public string ProductTypeName { get; set; }
        public Nullable<int> ProductTypeCode { get; set; }
    }
}
