//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoMac.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoHa7_Machine
    {
        public int MachineID { get; set; }
        public string MachineIpAdress { get; set; }
        public string MachineName { get; set; }
        public Nullable<bool> MachineActive { get; set; }
        public string MachineType { get; set; }
        public Nullable<int> GroupTable { get; set; }
        public Nullable<bool> ShowGroup { get; set; }
        public Nullable<bool> ShowFilterGroup { get; set; }
        public Nullable<int> Timer { get; set; }
        public string BackgroundColorToGo { get; set; }
        public string ForceColorTogo { get; set; }
        public string BackgroundColorChange { get; set; }
        public string ForceColorChange { get; set; }
        public string BackgroundColorEmergency { get; set; }
        public Nullable<int> FontSizePrint { get; set; }
        public Nullable<int> PaddingSizeHeader { get; set; }
        public string PrinterName { get; set; }
        public Nullable<bool> AutoPrinter { get; set; }
        public Nullable<int> AutoPrinterAfter { get; set; }
        public Nullable<bool> PrinterBarcode { get; set; }
        public Nullable<bool> MultiInstance { get; set; }
        public string SoundUrl { get; set; }
        public Nullable<int> TicketWidthSize { get; set; }
        public Nullable<int> TicketHeightSize { get; set; }
        public Nullable<int> TicketFontSize { get; set; }
        public string ForceColor { get; set; }
        public string ForceColor1 { get; set; }
        public string BackgrdColorQty { get; set; }
        public string ForceColorQty { get; set; }
        public Nullable<int> FontSizeQty { get; set; }
        public string ForceColorQty1 { get; set; }
    }
}
