//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoMac.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoHa7_ProcSaleItem
    {
        public int SaleItemID { get; set; }
        public Nullable<int> TicketID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> TicketNum { get; set; }
        public string Description { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Extra { get; set; }
        public string Employee { get; set; }
        public Nullable<bool> Done { get; set; }
        public Nullable<bool> ToKitchen { get; set; }
        public Nullable<bool> TakeOut { get; set; }
        public Nullable<bool> NotSaleItem { get; set; }
        public Nullable<bool> Done1 { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<bool> Cancel { get; set; }
        public Nullable<bool> IsChange { get; set; }
        public string BarCode { get; set; }
        public string ExtraName { get; set; }
        public string ExtraPrice { get; set; }
        public string OptionRequire { get; set; }
        public Nullable<bool> IsSmall { get; set; }
        public Nullable<int> MType { get; set; }
        public Nullable<int> SaleItemID_Root { get; set; }
        public string ExtraWith { get; set; }
        public string ExtraWithout { get; set; }
        public string CustomSelect { get; set; }
    }
}
