//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoMac.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoHa7_Sys_Role_Permission
    {
        public int RP_Role_ID { get; set; }
        public string RP_Object_ID { get; set; }
        public Nullable<int> RP_Permission { get; set; }
    
        public virtual PhoHa7_Sys_Object PhoHa7_Sys_Object { get; set; }
        public virtual PhoHa7_Sys_Role PhoHa7_Sys_Role { get; set; }
    }
}
