//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoMac.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoHa7_Sys_Object
    {
        public PhoHa7_Sys_Object()
        {
            this.PhoHa7_Sys_Role_Permission = new HashSet<PhoHa7_Sys_Role_Permission>();
            this.PhoHa7_Sys_User_Permission = new HashSet<PhoHa7_Sys_User_Permission>();
        }
    
        public string Syso_ID { get; set; }
        public string Syso_Name { get; set; }
        public string Syso_NameEn { get; set; }
        public string Syso_Parent_ID { get; set; }
        public string Syso_Description { get; set; }
        public Nullable<bool> Syso_Actived { get; set; }
    
        public virtual ICollection<PhoHa7_Sys_Role_Permission> PhoHa7_Sys_Role_Permission { get; set; }
        public virtual ICollection<PhoHa7_Sys_User_Permission> PhoHa7_Sys_User_Permission { get; set; }
    }
}
