//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoMac.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcTicket
    {
        public int TicketID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public int EmployeeID { get; set; }
        public int TicketNum { get; set; }
        public Nullable<System.DateTime> DateTimeIssue { get; set; }
        public Nullable<byte> PaidType { get; set; }
        public Nullable<int> ContractType { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> TotalS { get; set; }
        public Nullable<decimal> TotalP { get; set; }
        public Nullable<decimal> TotalG { get; set; }
        public Nullable<decimal> TotalE { get; set; }
        public Nullable<decimal> ShareOwn { get; set; }
        public Nullable<decimal> ShareEmp { get; set; }
        public Nullable<decimal> PaidCash { get; set; }
        public Nullable<decimal> PaidGift { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<int> ByWho { get; set; }
        public Nullable<int> TimeSpan { get; set; }
        public string DriverLicense { get; set; }
        public string CardCode { get; set; }
        public string GiftCode { get; set; }
        public Nullable<decimal> Tips { get; set; }
        public Nullable<decimal> TotalT { get; set; }
        public Nullable<decimal> TotalC { get; set; }
        public Nullable<decimal> PaidCredit { get; set; }
        public Nullable<decimal> PaidCheck { get; set; }
        public Nullable<bool> Voided { get; set; }
        public Nullable<bool> SkipTax { get; set; }
        public Nullable<bool> JackPot { get; set; }
        public Nullable<bool> VNDisComm { get; set; }
        public Nullable<bool> TableDone { get; set; }
        public Nullable<bool> Delivery { get; set; }
        public string XferTo { get; set; }
        public string CustomerName { get; set; }
        public string TableName { get; set; }
        public string BarCode { get; set; }
        public string VoiDelReason { get; set; }
        public Nullable<int> MemberType { get; set; }
        public Nullable<int> MealsType { get; set; }
        public Nullable<int> TabNum { get; set; }
        public Nullable<int> SeatNum { get; set; }
        public Nullable<int> ResInt4 { get; set; }
        public Nullable<decimal> Tax2 { get; set; }
        public Nullable<decimal> ProdDiscount { get; set; }
        public Nullable<decimal> PaidMember { get; set; }
        public Nullable<decimal> CoGDiscount { get; set; }
        public Nullable<decimal> CoGDiscountP { get; set; }
        public Nullable<System.DateTime> ResDate0 { get; set; }
        public Nullable<System.DateTime> ResDate1 { get; set; }
        public Nullable<System.DateTime> ResDate2 { get; set; }
        public Nullable<float> CommPercent { get; set; }
        public Nullable<decimal> CommProduct { get; set; }
        public Nullable<decimal> TotalO { get; set; }
        public Nullable<int> TranID { get; set; }
        public Nullable<int> DTicketNum { get; set; }
        public Nullable<bool> TakeOut { get; set; }
        public Nullable<int> TableID { get; set; }
        public Nullable<int> TabCatID { get; set; }
        public Nullable<int> TabParties { get; set; }
        public Nullable<bool> SplitCheck { get; set; }
        public Nullable<bool> CoG { get; set; }
        public Nullable<bool> ServerCard { get; set; }
        public Nullable<bool> IsHLProductSale { get; set; }
        public Nullable<bool> IsHLMemberSale { get; set; }
        public Nullable<bool> ResBool9 { get; set; }
        public string ResString5 { get; set; }
        public string ResString6 { get; set; }
        public string ResString7 { get; set; }
        public string ResString8 { get; set; }
        public string ResString9 { get; set; }
        public Nullable<decimal> LibProduct { get; set; }
        public Nullable<decimal> DHLMealCharge { get; set; }
        public Nullable<decimal> DHLCCardCharge { get; set; }
        public Nullable<decimal> DHLMCardCharge { get; set; }
        public Nullable<decimal> DUpGrade { get; set; }
        public Nullable<int> ResInt5 { get; set; }
        public Nullable<int> ResInt6 { get; set; }
        public Nullable<int> ResInt7 { get; set; }
        public Nullable<int> ResInt8 { get; set; }
        public Nullable<int> ResInt9 { get; set; }
        public Nullable<int> OnDay { get; set; }
        public Nullable<int> OnMonth { get; set; }
        public Nullable<int> OnYear { get; set; }
        public Nullable<System.DateTime> OnDate { get; set; }
        public string DateKey { get; set; }
        public Nullable<int> OnWeek { get; set; }
        public string WeekKey { get; set; }
        public Nullable<int> OnBiWeek { get; set; }
        public string BiWeekKey { get; set; }
        public Nullable<int> OnSimMonth { get; set; }
        public string SimMonthKey { get; set; }
        public Nullable<int> OnQuarter { get; set; }
        public string QuarterKey { get; set; }
        public Nullable<bool> NewObj { get; set; }
        public Nullable<bool> ChgeObj { get; set; }
        public Nullable<bool> SentObj { get; set; }
        public Nullable<decimal> PaidGCard { get; set; }
        public Nullable<decimal> PaidMisc { get; set; }
        public Nullable<int> AdminID { get; set; }
        public Nullable<int> PayrollID { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<int> CoachID { get; set; }
        public string CoachName { get; set; }
        public Nullable<int> SaleRepID { get; set; }
        public string SaleRepName { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<int> CardID { get; set; }
        public Nullable<bool> IsExterm { get; set; }
        public Nullable<System.DateTime> EditTimestamp { get; set; }
        public Nullable<int> RecordState { get; set; }
        public string RecordGUID { get; set; }
        public Nullable<bool> Done { get; set; }
        public Nullable<bool> ToGo { get; set; }
    }
}
