//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoMac.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Size
    {
        public Product_Size()
        {
            this.Product_SizeDetails = new HashSet<Product_SizeDetails>();
        }
    
        public int Size_ID { get; set; }
        public string Size_Code { get; set; }
        public string Size_Name { get; set; }
        public string Size_Description { get; set; }
        public Nullable<bool> Size_Actived { get; set; }
    
        public virtual ICollection<Product_SizeDetails> Product_SizeDetails { get; set; }
    }
}
