//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoMac.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_SizeDetails
    {
        public int PSize_ID { get; set; }
        public Nullable<int> PSize_Size_ID { get; set; }
        public Nullable<int> PSize_Product_ID { get; set; }
        public Nullable<decimal> PSize_Price { get; set; }
        public Nullable<decimal> PSize_ExtraPrice { get; set; }
    
        public virtual Product_Size Product_Size { get; set; }
        public virtual Product Product { get; set; }
    }
}
