//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoMac.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleItem
    {
        public int SaleItemID { get; set; }
        public int TicketID { get; set; }
        public int ProductID { get; set; }
        public Nullable<int> TicketNum { get; set; }
        public string Description { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> TPrice { get; set; }
        public Nullable<decimal> Extra { get; set; }
        public Nullable<int> ByWho { get; set; }
        public Nullable<decimal> ProcDiscount { get; set; }
        public Nullable<decimal> TeenDiscount { get; set; }
        public Nullable<decimal> SeniorDiscount { get; set; }
        public Nullable<bool> ComProd { get; set; }
        public Nullable<bool> PrintBoth { get; set; }
        public Nullable<bool> SmallSize { get; set; }
        public Nullable<bool> Done { get; set; }
        public Nullable<bool> ChociceNo { get; set; }
        public string SizeChoiceTxt { get; set; }
        public Nullable<int> TranID { get; set; }
        public Nullable<int> MType { get; set; }
        public Nullable<int> WorkTimeSec { get; set; }
        public Nullable<int> ItemPos { get; set; }
        public Nullable<decimal> ComTotal { get; set; }
        public Nullable<decimal> OrgPrice { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> TCost { get; set; }
        public Nullable<decimal> CoGDiscount { get; set; }
        public Nullable<decimal> CPrice { get; set; }
        public Nullable<decimal> SPrice { get; set; }
        public Nullable<bool> TakeOut { get; set; }
        public Nullable<bool> Printed { get; set; }
        public Nullable<int> PrintStation { get; set; }
        public Nullable<bool> NotSaleItem { get; set; }
        public string ItemCode { get; set; }
        public string KitchenName { get; set; }
        public Nullable<int> TabParty { get; set; }
        public Nullable<bool> NoTax { get; set; }
        public Nullable<bool> CoG { get; set; }
        public Nullable<bool> Voided { get; set; }
        public Nullable<bool> IsHLProductSale { get; set; }
        public Nullable<bool> IsHLMemberSale { get; set; }
        public Nullable<int> MemberType { get; set; }
        public Nullable<int> MealsType { get; set; }
        public Nullable<int> RewardPoints { get; set; }
        public string ProdNo { get; set; }
        public Nullable<int> QBuy { get; set; }
        public Nullable<int> QFree { get; set; }
        public Nullable<int> OnDay { get; set; }
        public Nullable<int> OnMonth { get; set; }
        public Nullable<int> OnYear { get; set; }
        public Nullable<System.DateTime> OnDate { get; set; }
        public string DateKey { get; set; }
        public Nullable<int> OnWeek { get; set; }
        public string WeekKey { get; set; }
        public Nullable<int> OnBiWeek { get; set; }
        public string BiWeekKey { get; set; }
        public Nullable<int> OnSimMonth { get; set; }
        public string SimMonthKey { get; set; }
        public Nullable<int> OnQuarter { get; set; }
        public string QuarterKey { get; set; }
        public Nullable<bool> NewObj { get; set; }
        public Nullable<bool> ChgeObj { get; set; }
        public Nullable<bool> SentObj { get; set; }
        public Nullable<float> OrgAmount { get; set; }
        public Nullable<float> TotAmount { get; set; }
        public Nullable<float> UnitAmount { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<int> CoachID { get; set; }
        public string CoachName { get; set; }
        public Nullable<int> SaleRepID { get; set; }
        public string SaleRepName { get; set; }
        public Nullable<byte> PaidType { get; set; }
        public Nullable<int> QtyAdj { get; set; }
        public Nullable<bool> IsGiftItem { get; set; }
        public Nullable<int> GiftItems { get; set; }
        public Nullable<int> FreeItems { get; set; }
        public string ProductName { get; set; }
        public string BarCode { get; set; }
        public string Location { get; set; }
        public string Serial { get; set; }
        public Nullable<bool> SerialNeeded { get; set; }
        public Nullable<int> StockHold { get; set; }
        public Nullable<bool> QuotedItem { get; set; }
        public Nullable<bool> bReserved { get; set; }
        public Nullable<bool> bAccessory { get; set; }
        public Nullable<int> PAccountType { get; set; }
        public Nullable<int> PAccountID { get; set; }
        public string PAccountName { get; set; }
        public string VendorName { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<int> RecordState { get; set; }
        public string RecordGUID { get; set; }
        public Nullable<System.DateTime> EditTimestamp { get; set; }
        public Nullable<int> AdminID { get; set; }
        public Nullable<float> Weight { get; set; }
        public string FoodTypeName { get; set; }
        public Nullable<int> FoodTypeID { get; set; }
    }
}
