//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoMac.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int TableID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> CurTicketNum { get; set; }
        public Nullable<int> CurDTicketNum { get; set; }
        public Nullable<bool> Active { get; set; }
        public string TableName { get; set; }
        public Nullable<int> ImageID { get; set; }
        public string ImageFPath { get; set; }
        public Nullable<int> Page { get; set; }
        public Nullable<int> Row { get; set; }
        public Nullable<int> Col { get; set; }
        public Nullable<int> ButtonColor { get; set; }
        public Nullable<int> TextColor { get; set; }
        public Nullable<bool> Delivery { get; set; }
        public Nullable<int> ZOrder { get; set; }
        public Nullable<int> TabNum { get; set; }
        public Nullable<int> SeatNum { get; set; }
        public Nullable<bool> TakeOut { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<bool> TActive { get; set; }
        public Nullable<int> OnDay { get; set; }
        public Nullable<int> OnMonth { get; set; }
        public Nullable<int> OnYear { get; set; }
        public Nullable<System.DateTime> OnDate { get; set; }
        public string DateKey { get; set; }
        public Nullable<int> OnWeek { get; set; }
        public string WeekKey { get; set; }
        public Nullable<int> OnBiWeek { get; set; }
        public string BiWeekKey { get; set; }
        public Nullable<int> OnSimMonth { get; set; }
        public string SimMonthKey { get; set; }
        public Nullable<int> OnQuarter { get; set; }
        public string QuarterKey { get; set; }
        public Nullable<bool> NewObj { get; set; }
        public Nullable<bool> ChgeObj { get; set; }
        public Nullable<bool> SentObj { get; set; }
        public Nullable<float> BottleOff { get; set; }
        public Nullable<int> objType { get; set; }
        public string oName { get; set; }
        public Nullable<int> oTextAlign { get; set; }
        public string oFontName { get; set; }
        public Nullable<float> oFontPoint { get; set; }
        public Nullable<int> oFontStyle { get; set; }
        public Nullable<int> oForeColor { get; set; }
        public Nullable<int> oBackColor { get; set; }
        public Nullable<int> oLocX { get; set; }
        public Nullable<int> oLocY { get; set; }
        public Nullable<int> oWidth { get; set; }
        public Nullable<int> oHeight { get; set; }
        public Nullable<int> oTableStyle { get; set; }
        public Nullable<int> oUpperColor { get; set; }
        public Nullable<int> oLowerColor { get; set; }
        public Nullable<int> RecordState { get; set; }
        public string RecordGUID { get; set; }
        public Nullable<int> TableType { get; set; }
        public Nullable<int> TableStatus { get; set; }
        public Nullable<bool> BarTab { get; set; }
        public Nullable<bool> FastCash { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public string CustomerName { get; set; }
        public string Description { get; set; }
    }
}
